GNUSTEP_MAKEFILES=/GNUstep/System/Library/Makefiles
include $(GNUSTEP_MAKEFILES)/common.make 

TOOL_NAME=CLuaFun
CLuaFun_OBJC_FILES=LuaTestClass.m  CLuaFun.m

include $(GNUSTEP_MAKEFILES)/tool.make 
